=== Bluscream/cvr-mods/mods.schema.json
{
	"type": "array",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "",
	"minItems": 1,
	"uniqueItems": true,
	"items": {
		"type": "object",
		"required": [
			"_id",
			"name",
			"modversion",
			"gameversion",
			"loaderversion",
			"modtype",
			"author",
			"description",
			"searchtags",
			"requirements",
			"downloadlink",
			"sourcelink",
			"changelog",
			"embedcolor"
		],
		"properties": {
			"_id": {
				"type": "number"
			},
			"name": {
				"type": "string",
				"minLength": 1
			},
			"modversion": {
				"type": "string",
				"minLength": 1
			},
			"gameversion": {
				"type": "string",
				"minLength": 1
			},
			"loaderversion": {
				"type": "string",
				"minLength": 1
			},
			"modtype": {
				"type": "string",
				"minLength": 1
			},
			"author": {
				"type": "string",
				"minLength": 1
			},
			"description": {
				"type": "string",
				"minLength": 1
			},
			"searchtags": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"requirements": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"downloadlink": {
				"type": "string",
				"minLength": 1
			},
			"sourcelink": {
				"type": "string",
				"minLength": 1
			},
			"changelog": {
				"type": "string",
				"minLength": 1
			},
			"embedcolor": {
				"type": "string",
				"minLength": 1
			}
		}
	}
}

=== Bluscream/cvr-mods/FreedomFingers/Properties/CVRMG.json
{
  "_id": 101,
  "name": "FreedomFingers",
  "modversion": "1.0.7",
  "gameversion": "2024r174",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "This removes the annoying index controller toggle to switch between finger tracking and animation, replacing it with a gesture lock toggle. Where your fingers are tracked **all** the time but you can pick whether you want gestures or not.\n\nYou can enable notifications in the melon config, to know whether the gestures are enabled or not.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/FreedomFingers) for more info.\n\n",
  "searchtags": [
    "index",
    "finger",
    "gesture",
    "toggle",
    "tracking"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r65/FreedomFingers.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/FreedomFingers",
  "changelog": "- Fixed for 2024r174",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/PostProcessingOverrides/Properties/CVRMG.json
{
  "_id": 140,
  "name": "PostProcessingOverrides",
  "modversion": "0.0.3",
  "gameversion": "2022r171p1",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "__**Features**__:\n- Enable/Disable/Force/Override Post processing configurations for the current world (persistent).\n- Choose between Original, Global, Custom, and Off for which Post Processing configuration type should be use for the current world.\n- Chose which Configuration Type a world gets when you join for the first time (via melon preferences).\n- While using Global or Custom, you can configure the settings to be: Off, Original, or Override.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/PostProcessingOverrides) for more in-depth info.\n\n",
  "searchtags": [
    "post",
    "processing",
    "overrides",
    "bloom"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r48/PostProcessingOverrides.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/PostProcessingOverrides",
  "changelog": "- Added bloom threshold override.\n- Fixed not overriding the PP in some worlds.",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/NotificationLog/Properties/CVRMG.json
{
	"$schema": "https://github.com/Bluscream/cvr-mods/raw/master/mod.schema.json",
	"_id": 204,
	"name": "MoreLogging",
	"modversion": "1.0.1",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple highly customizable `Mod` that logs\n\n- HUD Notifications\n- Instance Joins\n- Player joins/leaves\n- Prop Spawns\n- ChatBox Messages\n\nto your MelonLoader console and log\n\n",
	"searchtags": [
		"logger",
		"log",
		"hud",
		"chat",
		"notification"
	],
	"requirements": [ "[ChatBox (Optional)](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/ChatBox)" ],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/latest/download/MoreLogging.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/MoreLogging",
	"changelog": "- Initial release.",
	"embedcolor": "006CFF"
}

=== Bluscream/cvr-mods/PropSpawner/Properties/CVRMG.json
{
	"_id": -1,
	"name": "PropSpawner",
	"modversion": "2.0.0",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple `Mod` that allows you to auto-spawn certain props when you join\n\n",
	"searchtags": [
		"automation",
		"prop",
		"props"
	],
	"requirements": [],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/download/05%2F07%2F2024/PropSpawner.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/PropSpawner",
	"changelog": "- Initial release.",
	"embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/NavMeshFollower/Properties/CVRMG.json
{
  "_id": 194,
  "name": "NavMeshFollower",
  "modversion": "0.0.6",
  "gameversion": "2024r175",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Simple mod that allows to control a prop nav mesh agent.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/NavMeshFollower) for more in-depth info.\n\n",
  "searchtags": [
    "nav",
    "mesh",
    "agent",
    "ai",
    "prop"
  ],
  "requirements": ["[NavMeshTools](https://api.cvrmg.com/v1/mods/download/193)", "[RequestLib](https://api.cvrmg.com/v1/mods/download/169)", "[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r67/NavMeshFollower.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/NavMeshFollower",
  "changelog": "- Fixed for 2024r175\n- Prevent followers from making you seat when they're holding a prop with a seat",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/BetterCache/Properties/CVRMG.json
{
  "_id": 177,
  "name": "BetterCache",
  "modversion": "0.0.3",
  "gameversion": "2023r172",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Simple mod that improves the Cache management and cleaning.\n\n**__Features__**\n- Deletes the files with older accessed date when above the limit\n- Set a custom Cache Folder location (default: `ChilloutVR/Cache/`)\n- Set a Max limit for the Cache (default: `20GB`)\n- Buttons to clear cache\n- Deletes original Cache Folders to prevent cluttering\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/BetterCache) for more in-depth info.\n\n",
  "searchtags": [
    "better",
    "cache"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r60/BetterCache.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/BetterCache",
  "changelog": "- Stop poking cohtml outside of main thread.",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/LoginProfiles/Properties/CVRMG.json
{
  "_id": 65,
  "name": "LoginProfiles",
  "modversion": "1.0.5",
  "gameversion": "2024r174",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Allows to start CVR with different **credentials profiles** via steam Launch Options, or straight from the commandline.\n\n```--profile=profile_id```\n\nI normally use this to test sync stuff (where I need 2 clients). For this, you'd need to copy CVR files to another folder, and launch together with `--no-steam` launch option. In my case would be: `ChilloutVR.exe --profile=kafeijao --no-steam`",
  "searchtags": [
    "login",
    "profile",
    "profiles",
    "credentials"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r65/LoginProfiles.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/LoginProfiles",
  "changelog": "- Fixed for 2024r174",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/ChatBox/Properties/CVRMG.json
{
  "_id": 168,
  "name": "ChatBox",
  "modversion": "1.0.7",
  "gameversion": "2022r170",
  "loaderversion": "v0.5.7",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Communicate with other people in the instance using Text and **ChatBox**es!\n\n__**Features**__\n- Press `Y` or BTKUI button in the Misc section to send messages.\n- Heavily customizable via BKTUI settings menu in the Misc section.\n- Modify the notification sounds by replacing the files at `/UserData/Chatbox/`\n- Use bool animator param `ChatBox/Typing` or `#ChatBox/Typing`\n- View the ChatBox History window via the BTKUI button in the Misc section.\n- Press `Arrow up`/`Arrow down` to iterate through the sent messages. You can also click `Prev` if you're in VR.\n- Press `Insert` or `Auto` in VR to attempt to auto-complete usernames.\n- Use `@target-username` to mention people in messages.\n- Self moderation for individual players.\n- Profanity filter (needs to be populated).\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/ChatBox) for more in-depth info.\n\n",
  "searchtags": [
    "chat",
    "box",
    "chatbox",
    "mod",
    "network"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r53/ChatBox.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/ChatBox",
  "changelog": "- Initial Release.\n- Fix auto-completion.\n- Prevent msgs from OSC endpoints to override msgs sent by typing.\n- Added profanity filter.\n- Prevent seeing messages from blocked people.\n- Added self moderation, so you can override showing/hiding messages from specific people.\n Added interceptors (check API in github).\n- Refactored API.\n- Fixed Interceptors API.\n- LayerMask in static constructors is a nono in unity debug mode.",
  "embedcolor": "16C60C"
}
