=== Bluscream/cvr-mods/mods.schema.json
{
	"type": "array",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "",
	"minItems": 1,
	"uniqueItems": true,
	"items": {
		"type": "object",
		"required": [
			"_id",
			"name",
			"modversion",
			"gameversion",
			"loaderversion",
			"modtype",
			"author",
			"description",
			"searchtags",
			"requirements",
			"downloadlink",
			"sourcelink",
			"changelog",
			"embedcolor"
		],
		"properties": {
			"_id": {
				"type": "number"
			},
			"name": {
				"type": "string",
				"minLength": 1
			},
			"modversion": {
				"type": "string",
				"minLength": 1
			},
			"gameversion": {
				"type": "string",
				"minLength": 1
			},
			"loaderversion": {
				"type": "string",
				"minLength": 1
			},
			"modtype": {
				"type": "string",
				"minLength": 1
			},
			"author": {
				"type": "string",
				"minLength": 1
			},
			"description": {
				"type": "string",
				"minLength": 1
			},
			"searchtags": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"requirements": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"downloadlink": {
				"type": "string",
				"minLength": 1
			},
			"sourcelink": {
				"type": "string",
				"minLength": 1
			},
			"changelog": {
				"type": "string",
				"minLength": 1
			},
			"embedcolor": {
				"type": "string",
				"minLength": 1
			}
		}
	}
}

=== Bluscream/cvr-mods/HTTPServer/Properties/CVRMG.json
{
	"$schema": "https://github.com/Bluscream/cvr-mods/raw/master/mod.schema.json",
	"_id": -1,
	"author": "Bluscream",
	"changelog": "- Initial release.",
	"description": "`Plugin` that provides a API for other plugins and mods to listen to HTTP Requests (similar to OSC)\n\n",
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/latest/download/HTTPServer.dll",
	"embedcolor": "006CFF",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"modversion": "1.0.0",
	"name": "HTTPServer",
	"requirements": [],
	"searchtags": [
		"http",
		"https",
		"web",
		"server"
	],
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/HTTPServer"
}

=== Bluscream/cvr-mods/OSC/Properties/CVRMG.json
{
  "_id": 79,
  "name": "OSC",
  "modversion": "1.1.3",
  "gameversion": "2022r171",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "This mod enables interactions with ChilloutVR using OSC. It also focus on compatibility with existing applications. If something is not working create an [issue in github](https://github.com/kafeijao/Kafe_CVR_Mods/issues) and I will fix it asap.\n\n__**Avatar**__\n- Change into new avatars\n- Change/Read parameters\n__**Inputs**__\n- Control your avatar\n- Send actions to the game\n__**Props**__\n- Set/Read prop location\n- Set/Read synced params\n__**Tracking**__\n- Listen to tracking data (location/battery) from `Trackers`, `Controllers`, `HMD`, `Base Stations`, and `Play Space`.\n__**ChatBox**__\n- Send ChaBox messages and typing events\n\n__**New**__ [python library](https://github.com/kafeijao/cvr_osc_lib_py) to abstract this OSC API with examples!\n\nRefer to the [IN-DEPTH](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/OSC) documentation for more information.",
  "searchtags": [
    "osc",
    "input",
    "parameter",
    "props",
    "tracking"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r55-ex/OSC.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/OSC",
  "changelog": "- Fixed for 2022r171",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/MoreChatNotifications/Properties/CVRMG.json
{
	"$schema": "https://github.com/Bluscream/cvr-mods/raw/master/mod.schema.json",
	"_id": -1,
	"name": "MoreChatNotifications",
	"modversion": "1.0.0",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple `Mod` that allows you to send additional notifications to other players via the ChatBox mod like\n- World Download Percentage\n -Instance Switching\n -Instance Rejoining\n -VR Mode Switching\n -FBT Switching\n\n",
	"searchtags": [
		"chat",
		"chatbox",
		"notifications"
	],
	"requirements": [ "[ChatBox](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/ChatBox)" ],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/download//MoreChatNotifications.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/MoreChatNotifications",
	"changelog": "- Initial release.",
	"embedcolor": "006CFF"
}

=== Bluscream/cvr-mods/mods.json
[
  {
    "_id": 204,
    "name": "NotificationLog",
    "modversion": "1.0.1",
    "gameversion": "2024r175",
    "loaderversion": "v0.6.1",
    "modtype": "Mod",
    "author": "Bluscream",
    "description": "Simple highly customizable `Mod` that logs\n\n- HUD Notifications\n- Instance Joins\n- Player joins\n- Player leaves\n- Prop Spawns\n\nto your MelonLoader console and log\n\n",
    "searchtags": [
      "logger",
      "log",
      "hud"
    ],
    "requirements": [],
    "downloadlink": "https://api.cvrmg.com/v1/mods/files/204/3/NotificationLog.dll",
    "sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/NotificationLog",
    "changelog": "- Initial release.",
    "embedcolor": "006CFF"
  },
  {
    "_id": 206,
    "name": "PublicSafety",
    "modversion": "1.0.0",
    "gameversion": "2024r175",
    "loaderversion": "v0.6.1",
    "modtype": "Mod",
    "author": "Bluscream",
    "description": "Simple `Mod` that allows you to auto-set certain settings like\n\n- URL Whitelist\n- Advanced Safety\n- Discord/Steam Rich Presence\n\nwhen you join public instances\n\nIf you have recommendations on other settings that should be included, leave them on [Github](https://github.com/Bluscream/cvr-mods/issues/new) or [Discord](https://discord.com/users/467777925790564352) \n\n",
    "searchtags": [
      "safety",
      "security",
      "automation"
    ],
    "requirements": [],
    "downloadlink": "https://api.cvrmg.com/v1/mods/files/206/3/PublicSafety.dll",
    "sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/PublicSafety",
    "changelog": "- Initial release.",
    "embedcolor": "006CFF"
  },
  {
    "_id": 207,
    "name": "PropSpawner",
    "modversion": "1.0.0",
    "gameversion": "2024r175",
    "loaderversion": "v0.6.1",
    "modtype": "Mod",
    "author": "Bluscream",
    "description": "Slightly less simple `Mod` that allows you to auto-spawn certain props when you join a instance\n\nCheck the [Github Readme](https://github.com/Bluscream/cvr-mods/blob/master/PropSpawner/README.md) for more infos.\n\n",
    "searchtags": [
      "automation",
      "prop",
      "props"
    ],
    "requirements": [],
    "downloadlink": "https://api.cvrmg.com/v1/mods/files/207/5/PropSpawner.dll",
    "sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/PropSpawner",
    "changelog": "- Initial release.",
    "embedcolor": "006CFF"
  }
]

=== Bluscream/cvr-mods/PublicSafety/Properties/CVRMG.json
{
	"_id": -1,
	"name": "PublicSafety",
	"modversion": "1.0.0",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple `Mod` that logs allows you to auto-set certain settings (like URL whitelist) when you join public instances\n\n",
	"searchtags": [
		"safety",
		"security",
		"automation"
	],
	"requirements": [],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/download/05%2F05%2F2024/PublicSafety.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/PublicSafety",
	"changelog": "- Initial release.",
	"embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/QRCode/Properties/CVRMG.json
{
  "_id": -1,
  "name": "BetterAFK",
  "modversion": "0.0.1",
  "gameversion": "2023r171p2",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Read QRCodes with the CVR Camera.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/QRCode) for more in-depth info.\n\n",
  "searchtags": [
    "qr",
    "code",
    "camera"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r56/QRCode.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/QRCode",
  "changelog": "- Initial Release.",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/ChatLog/Properties/CVRMG.json
{
	"_id": -1,
	"name": "ChatLog",
	"modversion": "1.0.0",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple `Mod` that logs Chat Messages to your MelonLoader console and log\n\n",
	"searchtags": [
		"logger",
		"log",
		"chat",
		"chatbox"
	],
	"requirements": [],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/download//ChatLog.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/ChatLog",
	"changelog": "- Initial release.",
	"embedcolor": "006CFF"
}
