=== Bluscream/cvr-mods/mods.schema.json
{
	"type": "array",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "",
	"minItems": 1,
	"uniqueItems": true,
	"items": {
		"type": "object",
		"required": [
			"_id",
			"name",
			"modversion",
			"gameversion",
			"loaderversion",
			"modtype",
			"author",
			"description",
			"searchtags",
			"requirements",
			"downloadlink",
			"sourcelink",
			"changelog",
			"embedcolor"
		],
		"properties": {
			"_id": {
				"type": "number"
			},
			"name": {
				"type": "string",
				"minLength": 1
			},
			"modversion": {
				"type": "string",
				"minLength": 1
			},
			"gameversion": {
				"type": "string",
				"minLength": 1
			},
			"loaderversion": {
				"type": "string",
				"minLength": 1
			},
			"modtype": {
				"type": "string",
				"minLength": 1
			},
			"author": {
				"type": "string",
				"minLength": 1
			},
			"description": {
				"type": "string",
				"minLength": 1
			},
			"searchtags": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"requirements": {
				"type": "array",
				"items": {
					"required": [],
					"properties": {}
				}
			},
			"downloadlink": {
				"type": "string",
				"minLength": 1
			},
			"sourcelink": {
				"type": "string",
				"minLength": 1
			},
			"changelog": {
				"type": "string",
				"minLength": 1
			},
			"embedcolor": {
				"type": "string",
				"minLength": 1
			}
		}
	}
}

=== Bluscream/cvr-mods/Logger++/Properties/CVRMG.json
{
  "_id": 159,
  "name": "Logger++",
  "modversion": "0.0.7",
  "gameversion": "2024r175",
  "loaderversion": "v0.6.1",
  "modtype": "Plugin",
  "author": "kafeijao",
  "description": "Simple `Plugin` that redirects **and** filters unity logs to the Melon Loader console.\n\n__**Features**__\n- Enable/Disable filters (melon prefs).\n- Rate Limit the same log to only be printed every 5 secs max.\n- Enable full stack traces for `info`/`warning`/`error` Logs.\n\n**Note:** The IL offsets are not printed in the MelonLogger console because unity adds those internally :(\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/Logger++) for more in-depth info.\n\n",
  "searchtags": [
    "logger",
    "log",
    "debug"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r67/Logger++.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/Logger++",
  "changelog": "- Fixed for 2024r174",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/PickupOverrides/Properties/CVRMG.json
{
  "_id": 66,
  "name": "PickupOverrides",
  "modversion": "1.0.6",
  "gameversion": "2024r176",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Allows to override a few settings for all the pickups in the scene.\n\n__**Auto-Hold**__ whether the pickups will stick to your hand or not, to drop a Auto-Held pickup you need to squeeze the right grip and pull the thumbstick back (both on the **right** controller even if the pickup is held on the left controller)\n\n__**Maximum Grab Distance**__ sets the max distance you can actually grab a pickup. This is useful if you're tired of grabbing random pickups from across the world. Note: The pickups will still highlight meaning they can be tele-grabbed (the alyx style pull), but you won't be able to grab unless it is within the max distance.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/PickupOverrides) for more in-depth info.\n\n",
  "searchtags": [
    "pickup",
    "pickups",
    "auto",
    "hold",
    "grab",
    "distance",
    "overrides",
    "settings"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r72/PickupOverrides.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/PickupOverrides",
  "changelog": "- Fixed for 2024r175",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/RetroCVR/Properties/CVRMG.json
{
  "_id": -1,
  "name": "RetroCVR",
  "modversion": "0.0.1",
  "gameversion": "2023r173",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Adds LibRetro to CVR.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/RetroCVR) for more in-depth info.\n\n",
  "searchtags": [
    "retro",
    "lib",
    "libretro",
    "emulator",
    "emulation"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r62/RetroCVR.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/RetroCVR",
  "changelog": "- Initial Release.",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/VRModeSwitchHotkey/Properties/CVRMG.json
{
	"$schema": "https://github.com/Bluscream/cvr-mods/raw/master/mod.schema.json",
	"_id": -1,
	"name": "VRModeSwitchHotkey",
	"modversion": "1.0.0",
	"gameversion": "2024r175",
	"loaderversion": "v0.6.1",
	"modtype": "Mod",
	"author": "Bluscream",
	"description": "Simple `Mod` that allows you to switch between VR/Desktop mode with a simple configurable modifier+hotkey combo (works with virtual keyboards) \n\n",
	"searchtags": [
		"hotkey",
		"workaround",
		"virtualdesktop"
	],
	"requirements": [],
	"downloadlink": "https://github.com/Bluscream/cvr-mods/releases/latest/download/VRModeSwitchHotkey.dll",
	"sourcelink": "https://github.com/Bluscream/cvr-mods/tree/master/VRModeSwitchHotkey",
	"changelog": "- Initial release.",
	"embedcolor": "006CFF"
}

=== Bluscream/cvr-mods/CCK.Debugger/Properties/CVRMG.json
{
  "_id": 74,
  "name": "CCK.Debugger",
  "modversion": "2.0.10",
  "gameversion": "2024r174",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "The Content Creation Debugger allows you to debug `avatars`, `props` and `misc`.\n\n__**Menu**__ - Menu that displays useful information like:\n- Avatar and Props `synced`/`local` parameter values\n- Prop Pickups and Attach Info\n- Avatar & Props Pointers/Triggers detailed info\n- Avatar animator layer playing clips\n\n__**Visualizers**__ - Toggleable Component visualizers:\n- Pointers and Triggers 3D shape\n- Trigger `OnEnter` (green), `OnExit` (red), `OnStay` (yellow) events\n- IK bones\n- FBT Trackers\n\nSupports [BTKUILib](https://api.cvrmg.com/v1/mods/download/113) to restore the menu position or completely hide it.\n\nClick [here](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/CCK.Debugger) for a more **in-depth** readme (with pictures).",
  "searchtags": [
    "cck",
    "debug",
    "debugger",
    "menu",
    "avatar",
    "prop",
    "pointer",
    "trigger",
    "visualizer",
    "animator",
    "layer"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r65/CCK.Debugger.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/CCK.Debugger",
  "changelog": "- Fixed for 2024r174\n- Added new curl and spread finger info\n- Removed eye movement visualizers",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/GrabbyBones/Properties/CVRMG.json
{
  "_id": 160,
  "name": "GrabbyBones",
  "modversion": "1.0.2",
  "gameversion": "2022r171p1",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Adds grabbing to `Dynamic Bones` and `Magica Cloth Bones`.\n\n__**Features**__\n- Uses the bone's radius configuration for grabbing radius.\n- Sets animator parameters. Check [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/GrabbyBones)\n- Can be disabled for specific scripts using `[NGB]` tag on the game object name.\n- Prevent grabbing a specific bone within a script using `[NGBB]` tag on the bone's game object name.\n\n__**Notes**__\n- If you find broken avatars share the avatar and contact me.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/GrabbyBones) for more in-depth info.\n\n",
  "searchtags": [
    "grab",
    "bones",
    "grabby",
    "physbones",
    "bone"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r53/GrabbyBones.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/GrabbyBones",
  "changelog": "- Added the tag `[NGBB]` to prevent grabbing specific bones.\n- Fixed enabled config not disabling properly.\n- Fixed angle parameter being wrongly calculated",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/RequestLib/Properties/CVRMG.json
{
  "_id": 169,
  "name": "RequestLib",
  "modversion": "0.0.12",
  "gameversion": "2024r175ex1",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "The Request Lib is a Mod that allows users to receive requests from other players in the same instance via the Mod Network.\n\nThis will enable mods to ask permission for things to players without both having a specific mod. For example if both players have the **RequestLib**, this will allow the `Player 1` with the **TeleportRequest** mod to request to teleport to `Player 2` even if the `Player 2` doesn't have the **TeleportRequest** mod.\n\n__**Features**__\n- Receive requests from remote players via the Mod Network.\n- Similarly to invites, you receive:\n - Hud message icon\n - Quick Menu notification with `Accept`/`Decline`\n - Main Menu Messages Tab named `Mod Requests`\n- Fully customizable permissions that allow requests to be asked, auto-accepted, or auto-declined\n- Several permissions granularity, they can be global, per player, and even per player + mod combo.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/RequestLib) for more in-depth info including the `API` to add this to your mods.\n\n",
  "searchtags": [
    "request",
    "lib"
  ],
  "requirements": ["[BTKUILib](https://api.cvrmg.com/v1/mods/download/113)"],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r66/RequestLib.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/RequestLib",
  "changelog": "- Added a listener on the receiver of the request when the response is about to get sent. This is useful when you want to do something with the request result (since auto-accept/decline exist you wouldn't be able to intercept those without this)",
  "embedcolor": "16C60C"
}

=== Bluscream/cvr-mods/NavMeshTools/Properties/CVRMG.json
{
  "_id": -1,
  "name": "NavMeshTools",
  "modversion": "0.0.1",
  "gameversion": "2023r172",
  "loaderversion": "v0.6.1",
  "modtype": "Mod",
  "author": "kafeijao",
  "description": "Simple library that allows to bake NavMeshes in Runtime.\n\nCheck [README.md](https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/NavMeshTools) for more in-depth info.\n\n",
  "searchtags": [
    "nav",
    "mesh",
    "agent",
    "ai",
    "path"
  ],
  "requirements": [],
  "downloadlink": "https://github.com/kafeijao/Kafe_CVR_Mods/releases/download/r60/NavMeshTools.dll",
  "sourcelink": "https://github.com/kafeijao/Kafe_CVR_Mods/tree/master/NavMeshTools",
  "changelog": "- Initial Release.",
  "embedcolor": "16C60C"
}
